# mysql connect configuration
mysql:
  host: '127.0.0.1'
  port: 3306
  database: 'beego_admin'
  username: 'root'
  password: 'root'

login:
  captcha: 1

# attachment configuration
attachment:
  thumb_path: '/static/attachment/thumbnail/'
  path: 'static/uploads/attachment/'
  url: 'static/uploads/attachment/'
  validate_size: 52428800
  validate_ext: 'bmp,ico,psd,jpg,jpeg,png,gif,doc,docx,xls,xlsx,pdf,zip,rar,7z,tz,mp3,mp4,mov,swf,flv,avi,mpg,ogg,wav,flac,ape'